services:
  backend:
    build: ./backend
    container_name: backend-moodle
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - nginx_proxy
      - opotest
    ports:
      - "8000:8000"

  frontend-exam:
    build: ./frontend-exam
    container_name: frontend-exam-moodle
    restart: always
    networks:
      - nginx_proxy
    ports:
      - "4321:4321"

networks:
  nginx_proxy:
    external: true
  opotest:
    external: true
