"""test

Revision ID: ebcc4f8f4dc4
Revises: 
Create Date: 2025-11-09 12:46:07.838043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'ebcc4f8f4dc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_fk_if_exists(table_name: str, constraint_name: str | None) -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing = {fk["name"] for fk in inspector.get_foreign_keys(table_name)}
    targets = existing if constraint_name is None else {constraint_name}
    for name in targets:
        if name in existing:
            op.drop_constraint(name, table_name, type_="foreignkey")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'show_score',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_percentile',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_score_full',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam_official_result', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))
    _drop_fk_if_exists('exam_official_result', op.f('fk_exam_official_result_exam'))
    _drop_fk_if_exists('exam_official_result', op.f('fk_exam_official_result_user'))
    op.create_foreign_key('fk_exam_official_result_user_new', 'exam_official_result', 'exam_user', ['user_id'], ['id'])
    op.create_foreign_key('fk_exam_official_result_exam_new', 'exam_official_result', 'exam', ['exam_id'], ['id'])
    op.alter_column('exam_user', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.create_unique_constraint(None, 'exam_user', ['dni'])
    _drop_fk_if_exists('user_exam_submission', op.f('fk_user_exam_submission_user'))
    op.create_foreign_key('fk_user_exam_submission_user_new', 'user_exam_submission', 'exam_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_fk_if_exists('user_exam_submission', 'fk_user_exam_submission_user_new')
    op.create_foreign_key(op.f('fk_user_exam_submission_user'), 'user_exam_submission', 'exam_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_user', type_='unique')
    op.alter_column('exam_user', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('current_timestamp(6)'))
    _drop_fk_if_exists('exam_official_result', 'fk_exam_official_result_exam_new')
    _drop_fk_if_exists('exam_official_result', 'fk_exam_official_result_user_new')
    op.create_foreign_key(op.f('fk_exam_official_result_user'), 'exam_official_result', 'exam_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_exam_official_result_exam'), 'exam_official_result', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_official_result', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.alter_column('exam', 'show_score_full',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_percentile',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_score',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
