"""test

Revision ID: ebcc4f8f4dc4
Revises: 
Create Date: 2025-11-09 12:46:07.838043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebcc4f8f4dc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'show_score',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_percentile',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_score_full',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam_official_result', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.drop_constraint(op.f('fk_exam_official_result_exam'), 'exam_official_result', type_='foreignkey')
    op.drop_constraint(op.f('fk_exam_official_result_user'), 'exam_official_result', type_='foreignkey')
    op.create_foreign_key(None, 'exam_official_result', 'exam_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'exam_official_result', 'exam', ['exam_id'], ['id'])
    op.alter_column('exam_user', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.create_unique_constraint(None, 'exam_user', ['dni'])
    op.drop_constraint(op.f('fk_user_exam_submission_user'), 'user_exam_submission', type_='foreignkey')
    op.create_foreign_key(None, 'user_exam_submission', 'exam_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_exam_submission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_exam_submission_user'), 'user_exam_submission', 'exam_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_user', type_='unique')
    op.alter_column('exam_user', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.drop_constraint(None, 'exam_official_result', type_='foreignkey')
    op.drop_constraint(None, 'exam_official_result', type_='foreignkey')
    op.create_foreign_key(op.f('fk_exam_official_result_user'), 'exam_official_result', 'exam_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_exam_official_result_exam'), 'exam_official_result', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_official_result', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('current_timestamp(6)'))
    op.alter_column('exam', 'show_score_full',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_percentile',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exam', 'show_score',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
