ALTER TABLE exam_official_result
  ADD COLUMN score DOUBLE NULL DEFAULT NULL,
  ADD COLUMN merits DOUBLE NULL DEFAULT NULL;

ALTER TABLE exam
  ADD COLUMN use_official_scores BOOLEAN NOT NULL DEFAULT FALSE;
